---
- name: Configure Alpine on rpi
  hosts: rpi-user
  gather_facts: true
  remote_user: u0
  vars:
    ansible_python_interpreter: /usr/bin/python
    runtime_dir: "/run/user/{{ ansible_facts['user_id'] if ansible_facts['user_id'] is defined else lookup('pipe', 'id -u {{ remote_user }}') }}"
  
  vars_files:
    - env.yaml

  tasks:
    - name: Install needed packages
      community.general.apk:
        name:
          - adwaita-icon-theme
          - adw-gtk3
          - bluez
          - brightnessctl
          - dbus
          - dbus-openrc
          - dbus-x11
          - cage
          - elogind
          - firefox-esr
          - font-dejavu
          - foot
          - greetd
          - greetd-gtkgreet
          - grim
          - i3status
          - iwd
          - iwgtk
          - mako
          - mate-polkit
          - openrc-user
          - openrc-user-pam
          - playerctl
          - pipewire
          - pipewire-spa-bluez
          - pipewire-pulse
          - polkit
          - polkit-elogind
          - slurp
          - sway
          - swaybg
          - swaylock
          - swaylockd
          - swayidle
          - util-linux-login
          - waydroid
          - wireplumber
          - wl-clipboard
          - wvkbd
          - wvkbd-deskintl
          - wpa_supplicant
          - xwayland
          - flatpak
          - xdg-user-dirs
          - wireguard-tools
          - neovim
          - bash
          - bash-completion
          - gstreamer
          - gst-plugins-base
          - gst-plugins-good
          - waybar
          - virt-manager
          - incus
          - incus-client
          - bridge
        state: present
        update_cache: true
      become: true
      become_method: doas
      become_user: root

    - name: Init Waydroid with GAPPS
      ansible.builtin.command: waydroid init -s GAPPS
      become: true
      become_method: doas
      become_user: root

    - name: Copy the sway-session script
      ansible.builtin.copy:
        src: files/sway-session
        dest: /usr/local/bin/sway-session
        mode: '0755'
      become: true
      become_method: doas

    - name: Copy the waydroid-session script
      ansible.builtin.copy:
        src: files/waydroid-session
        dest: /usr/local/bin/waydroid-session
        mode: '0755'
      become: true
      become_method: doas

    - name: Create greetd config dir
      ansible.builtin.file:
        path: /etc/greetd
        state: directory
        mode: '0755'
      become: true
      become_method: doas

    - name: Copy the sway-config used by greetd
      ansible.builtin.copy:
        src: files/greetd/sway-config
        dest: /etc/greetd/sway-config
        mode: '0755'
      become: true
      become_method: doas

    - name: Copy greetd config
      ansible.builtin.copy:
        src: files/greetd/config.toml
        dest: /etc/greetd/config.toml
        mode: '0644'
      become: true
      become_method: doas

    - name: Copy greetd environments file
      ansible.builtin.copy:
        src: files/greetd/environments
        dest: /etc/greetd/environments
        mode: '0644'
      become: true
      become_method: doas

    - name: OpenRC enable required services
      ansible.builtin.service:
        name: "{{ item.service_name }}"
        runlevel: "{{ item.runlevel }}"
        enabled: true
      become: true
      become_method: doas
      become_user: root
      loop:
        - { service_name: 'bluetooth', runlevel: 'default' }
        - { service_name: 'cgroups', runlevel: 'default' }
        - { service_name: 'dbus', runlevel: 'default' }
        - { service_name: 'elogind', runlevel: 'default' }
        - { service_name: 'greetd', runlevel: 'default' }
        - { service_name: 'polkit', runlevel: 'default' }
        - { service_name: 'waydroid-container', runlevel: 'default' }
        - { service_name: 'ntpd', runlevel: 'default' }
        - { service_name: 'incusd', runlevel: 'default' }

    - name: OpenRC start required services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      become: true
      become_method: doas
      become_user: root
      loop:
        - bluetooth
        - cgroups
        - dbus
        - elogind
        - greetd
        - polkit
        - waydroid-container
        - incusd

    - name: Add flathub
      ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      become: true
      become_method: doas
      become_user: root

    - name: Add flathub for the current user
      ansible.builtin.command: flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      become: false

    - name: Create rc.conf dir
      ansible.builtin.file:
        path: ~/.config/rc
        state: directory
        mode: '0755'
      become: false

    - name: Allow propagation of the $WAYLAND_DISPLAY and associated environment variables
      ansible.builtin.copy:
        dest: ~/.config/rc/rc.conf
        content: |
          rc_env_allow="WAYLAND_DISPLAY"
      become: false

    - name: Create a custom gui user runlevel
      ansible.builtin.file:
        path: ~/.config/rc/runlevels/gui
        state: directory
        mode: '0755'
      become: false

    - name: Enable user services
      ansible.builtin.shell: |
        set -e
        rc-update -U add dbus gui
        rc-update -U add mako gui
        rc-update -U add pipewire gui
        rc-update -U add pipewire-pulse gui
        rc-update -U add wireplumber gui
      environment:
        XDG_RUNTIME_DIR: "{{ runtime_dir }}"
      become: false

    - name: Run Sway setup role
      ansible.builtin.include_role:
        name: sway_setup

    - name: Run Firefox universal setup role
      ansible.builtin.include_role:
        name: firefox_setup

    - name: Add bridge interface
      ansible.builtin.copy:
        dest: /etc/network/interfaces
        content: |
          auto lo
          iface lo inet loopback
          iface lo inet6 loopback

          auto br0
          iface br0
            bridge_ports eth0
            bridge_stp off
            address 192.168.15.7/24
            gateway 192.168.15.1
            address fd5d:d97c:25d5:1::7/64
            gateway fe80::920a:62ff:fe4f:28d0
      become: true
      become_method: doas
      become_user: root

    - name: Configure resolvconf
      ansible.builtin.copy:
        dest: /etc/network/interfaces
        content: |
          resolv_conf=/etc/resolv.conf
          name_servers="192.168.15.4 fd5d:d97c:25d5:1::4"
      become: true
      become_method: doas
      become_user: root

    - name: Init incus with a preseed file
      ansible.builtin.command:
        cmd: incus admin init --preseed
        stdin: "{{ lookup('ansible.builtin.file', 'files/incus/preseed.yaml') }}"
      changed_when: false
      become: true
      become_method: doas
      become_user: root
      tags:
        - incus

    - name: Set the pi-hole incus profile
      ansible.builtin.command:
        cmd: incus profile create pihole
        stdin: "{{ lookup('ansible.builtin.file', 'files/incus/profiles/pihole.yaml') }}"
      register: incus_profile_pihole
      failed_when: 
        - incus_profile_pihole.rc != 0
        - "'already exists' not in incus_profile_pihole.stderr and 'already exists' not in incus_profile_pihole.stdout"
      changed_when: incus_profile_pihole.rc == 0
      become: true
      become_method: doas
      become_user: root
      tags: incus

    - name: Create pi-hole container
      ansible.builtin.command:
        cmd: >
          incus launch images:debian/13/cloud pihole --profile default --profile pihole
      register: incus_launch_pihole
      failed_when: 
        - incus_profile_pihole.rc != 0
        - "'already exists' not in incus_profile_pihole.stderr and 'already exists' not in incus_profile_pihole.stdout"
      changed_when: incus_profile_pihole.rc == 0
      become: true
      become_method: doas
      become_user: root
      tags: incus

- name: Configure Pi-hole
  hosts: pihole
  gather_facts: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - env.yaml

  tasks:
    - name: Check pihole-FTL command
      ansible.builtin.shell: which pihole-FTL
      register: pihole_status
      changed_when: false
      failed_when: false

    - name: Manual Pi-hole setup
      ansible.builtin.pause:
        prompt: |
          SSH into your your Pi-hole instance and proceed with the installation using this command:
          curl -sSL https://install.pi-hole.net | bash
      when: pihole_status.rc != 0

    - name: Install needed packages
      ansible.builtin.apt:
        pkg:
          - dnscrypt-proxy
          - wireguard-tools

    - name: Copy dnscrypt-proxy config
      ansible.builtin.copy:
        src: files/dnscrypt-proxy/dnscrypt-proxy.toml
        dest: /etc/dnscrypt-proxy/dnscrypt-proxy.toml
        backup: true
    
    - name: Copy dnscrypt-proxy cloaking-rules
      ansible.builtin.copy:
        src: files/dnscrypt-proxy/cloaking-rules.txt
        dest: /etc/dnscrypt-proxy/cloaking-rules.txt
        backup: true

    - name: Copy dnscrypt-proxy forwarding-rules
      ansible.builtin.copy:
        src: files/dnscrypt-proxy/forwarding-rules.txt
        dest: /etc/dnscrypt-proxy/forwarding-rules.txt
        backup: true

    - name: Ensure the /etc/systemd/system/dnscrypt-proxy.socket.d dir exists
      ansible.builtin.file:
        path: /etc/systemd/system/dnscrypt-proxy.socket.d
        state: directory
        mode: '0755'

    - name: Set the dnscrypt-proxy systemd override
      ansible.builtin.copy:
        dest: /etc/systemd/system/dnscrypt-proxy.socket.d/override.conf
        mode: '0644'
        content: |
          [Socket]
          ListenStream=
          ListenDatagram=
          ListenStream=127.0.0.1:5053
          ListenDatagram=127.0.0.1:5053
      notify: Restart dnscrypt-proxy socket

    - name: Force systemd-resolved config file
      ansible.builtin.copy:
        dest: /etc/systemd/resolved.conf
        backup: yes
        content: |
          # Managed by Ansible
          [Resolve]
          DNS=127.0.0.1 ::1
          Domains=~.
          Cache=no
      notify: Restart systemd-resolved

  handlers:
    - name: Restart dnscrypt-proxy socket
      ansible.builtin.systemd_service:
        name: dnscrypt-proxy.socket
        state: reloaded
    - name: Restart systemd-resolved
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted
        enabled: yes
  