---
- name: Configure Alpine on rpi
  hosts: rpi-user
  gather_facts: true
  remote_user: u0
  vars:
    ansible_python_interpreter: /usr/bin/python
    runtime_dir: "/run/user/{{ ansible_facts['user_id'] if ansible_facts['user_id'] is defined else lookup('pipe', 'id -u {{ remote_user }}') }}"
  
  vars_files:
    - env.yaml

  tasks:
    - name: Install needed packages
      community.general.apk:
        name:
          - adwaita-icon-theme
          - adw-gtk3
          - bluez
          - brightnessctl
          - dbus
          - dbus-openrc
          - dbus-x11
          - cage
          - elogind
          - firefox-esr
          - font-dejavu
          - foot
          - greetd
          - greetd-gtkgreet
          - grim
          - i3status
          - iwd
          - iwgtk
          - mako
          - mate-polkit
          - openrc-user
          - openrc-user-pam
          - playerctl
          - pipewire
          - pipewire-spa-bluez
          - pipewire-pulse
          - polkit
          - polkit-elogind
          - slurp
          - sway
          - swaybg
          - swaylock
          - swaylockd
          - swayidle
          - util-linux-login
          - waydroid
          - wireplumber
          - wl-clipboard
          - wvkbd
          - wvkbd-deskintl
          - wpa_supplicant
          - xwayland
        state: present
        update_cache: true
      become: true
      become_method: doas
      become_user: root

    - name: Init Waydroid with GAPPS
      ansible.builtin.command: waydroid init -s GAPPS
      become: true
      become_method: doas
      become_user: root

    - name: Copy the sway-session script
      ansible.builtin.copy:
        src: files/sway-session
        dest: /usr/local/bin/sway-session
        mode: '0755'
      become: true
      become_method: doas

    - name: Copy the waydroid-session script
      ansible.builtin.copy:
        src: files/waydroid-session
        dest: /usr/local/bin/waydroid-session
        mode: '0755'
      become: true
      become_method: doas

    - name: Create greetd config dir
      ansible.builtin.file:
        path: /etc/greetd
        state: directory
        mode: '0755'
      become: true
      become_method: doas

    - name: Copy the sway-config used by greetd
      ansible.builtin.copy:
        src: files/greetd/sway-config
        dest: /etc/greetd/sway-config
        mode: '0755'
      become: true
      become_method: doas

    - name: Copy greetd config
      ansible.builtin.copy:
        src: files/greetd/config.toml
        dest: /etc/greetd/config.toml
        mode: '0644'
      become: true
      become_method: doas

    - name: Copy greetd environments file
      ansible.builtin.copy:
        src: files/greetd/environments
        dest: /etc/greetd/environments
        mode: '0644'
      become: true
      become_method: doas

    - name: OpenRC enable required services
      ansible.builtin.service:
        name: "{{ item.service_name }}"
        runlevel: "{{ item.runlevel }}"
        enabled: true
      become: true
      become_method: doas
      become_user: root
      loop:
        - { service_name: 'bluetooth', runlevel: 'default' }
        - { service_name: 'cgroups', runlevel: 'default' }
        - { service_name: 'dbus', runlevel: 'default' }
        - { service_name: 'elogind', runlevel: 'default' }
        - { service_name: 'greetd', runlevel: 'default' }
        - { service_name: 'polkit', runlevel: 'default' }
        - { service_name: 'waydroid-container', runlevel: 'default' }

    - name: OpenRC enable required services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      become: true
      become_method: doas
      become_user: root
      loop:
        - bluetooth
        - cgroups
        - dbus
        - elogind
        - greetd
        - polkit
        - waydroid-container

    - name: Create rc.conf dir
      ansible.builtin.file:
        path: ~/.config/rc
        state: directory
        mode: '0755'
      become: false

    - name: Allow propagation of the $WAYLAND_DISPLAY and associated environment variables
      ansible.builtin.copy:
        dest: ~/.config/rc/rc.conf
        content: |
          rc_env_allow="WAYLAND_DISPLAY"
      become: false

    - name: Create a custom gui user runlevel
      ansible.builtin.file:
        path: ~/.config/rc/runlevels/gui
        state: directory
        mode: '0755'
      become: false

    - name: Enable user services
      ansible.builtin.shell: |
        set -e
        rc-update -U add dbus gui
        rc-update -U add mako gui
        rc-update -U add pipewire gui
        rc-update -U add pipewire-pulse gui
        rc-update -U add wireplumber gui
      environment:
        XDG_RUNTIME_DIR: "{{ runtime_dir }}"
      become: false

    - name: Run Sway setup role
      ansible.builtin.include_role:
        name: sway_setup

    - name: Run Firefox universal setup role
      ansible.builtin.include_role:
        name: firefox_setup
